// Auto-generated file - do not edit manually
// Generated at: 2025-08-25T11:42:24.693Z

import { GalleryWithItems } from "@/types/gallery";

export const generatedGalleries: GalleryWithItems[] = [
  {
    "id": "portrait-gallery",
    "title": "Portrait Collection",
    "description": "Beautiful portrait photography showcasing people and emotions",
    "isPublic": true,
    "createdAt": "2025-07-14T01:42:26.474Z",
    "updatedAt": "2025-07-14T01:42:26.474Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-portrait-gallery-0",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/image_05.webp",
          "createdAt": "2025-07-26T04:01:51.629Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-1",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/image_11.webp",
          "createdAt": "2025-05-22T12:58:14.869Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-2",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_01.webp",
          "createdAt": "2025-06-29T15:37:56.455Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-3",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_06.webp",
          "createdAt": "2025-07-21T15:11:49.459Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-4",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_08.webp",
          "createdAt": "2025-06-27T11:56:15.426Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-5",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-6",
        "memoryType": "image",
        "position": 5,
        "caption": "Photo 6",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-6",
          "title": "Photo 6",
          "description": "Beautiful photo 6 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_12.webp",
          "createdAt": "2025-03-08T21:15:51.362Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-6",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-7",
        "memoryType": "image",
        "position": 6,
        "caption": "Photo 7",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-7",
          "title": "Photo 7",
          "description": "Beautiful photo 7 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_13.webp",
          "createdAt": "2025-03-25T03:36:45.025Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-7",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-8",
        "memoryType": "image",
        "position": 7,
        "caption": "Photo 8",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-8",
          "title": "Photo 8",
          "description": "Beautiful photo 8 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/photo_15.webp",
          "createdAt": "2025-08-19T13:19:59.681Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-8",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-9",
        "memoryType": "image",
        "position": 8,
        "caption": "Photo 9",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-9",
          "title": "Photo 9",
          "description": "Beautiful photo 9 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/picture_03.webp",
          "createdAt": "2025-07-07T00:01:16.748Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-9",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-10",
        "memoryType": "image",
        "position": 9,
        "caption": "Photo 10",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-10",
          "title": "Photo 10",
          "description": "Beautiful photo 10 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/picture_07.webp",
          "createdAt": "2025-04-06T09:57:46.759Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-10",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-11",
        "memoryType": "image",
        "position": 10,
        "caption": "Photo 11",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-11",
          "title": "Photo 11",
          "description": "Beautiful photo 11 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/picture_10.webp",
          "createdAt": "2025-07-18T01:06:07.622Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-11",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-12",
        "memoryType": "image",
        "position": 11,
        "caption": "Photo 12",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-12",
          "title": "Photo 12",
          "description": "Beautiful photo 12 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/picture_14.webp",
          "createdAt": "2025-03-19T02:58:19.882Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-12",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-13",
        "memoryType": "image",
        "position": 12,
        "caption": "Photo 13",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-13",
          "title": "Photo 13",
          "description": "Beautiful photo 13 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/shot_02.webp",
          "createdAt": "2025-03-17T00:28:29.507Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-13",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-14",
        "memoryType": "image",
        "position": 13,
        "caption": "Photo 14",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-14",
          "title": "Photo 14",
          "description": "Beautiful photo 14 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/shot_04.webp",
          "createdAt": "2025-07-21T22:49:33.191Z",
          "metadata": {}
        }
      },
      {
        "id": "item-portrait-gallery-14",
        "galleryId": "portrait-gallery",
        "memoryId": "memory-portrait-gallery-15",
        "memoryType": "image",
        "position": 14,
        "caption": "Photo 15",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T01:42:26.474Z",
        "updatedAt": "2025-07-14T01:42:26.474Z",
        "memory": {
          "id": "memory-portrait-gallery-15",
          "title": "Photo 15",
          "description": "Beautiful photo 15 from Portrait Collection",
          "type": "image",
          "url": "/mock/galleries/portrait-gallery/shot_09.webp",
          "createdAt": "2025-05-28T11:41:30.847Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 15,
    "isOwner": true
  },
  {
    "id": "landscape-gallery",
    "title": "Landscape Photography",
    "description": "Stunning landscapes from around the world",
    "isPublic": true,
    "createdAt": "2025-03-04T15:39:42.995Z",
    "updatedAt": "2025-03-04T15:39:42.995Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-landscape-gallery-0",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/image_03.webp",
          "createdAt": "2025-03-24T13:31:43.668Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-1",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/image_11.webp",
          "createdAt": "2025-07-09T09:26:09.399Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-2",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/image_12.webp",
          "createdAt": "2025-05-10T02:31:55.623Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-3",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/photo_13.webp",
          "createdAt": "2025-07-22T18:13:48.372Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-4",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/photo_15.webp",
          "createdAt": "2025-05-12T15:25:47.832Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-5",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-6",
        "memoryType": "image",
        "position": 5,
        "caption": "Photo 6",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-6",
          "title": "Photo 6",
          "description": "Beautiful photo 6 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/picture_04.webp",
          "createdAt": "2025-05-27T11:07:05.208Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-6",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-7",
        "memoryType": "image",
        "position": 6,
        "caption": "Photo 7",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-7",
          "title": "Photo 7",
          "description": "Beautiful photo 7 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/picture_05.webp",
          "createdAt": "2025-06-04T16:56:44.106Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-7",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-8",
        "memoryType": "image",
        "position": 7,
        "caption": "Photo 8",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-8",
          "title": "Photo 8",
          "description": "Beautiful photo 8 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/picture_06.webp",
          "createdAt": "2025-08-16T04:30:05.112Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-8",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-9",
        "memoryType": "image",
        "position": 8,
        "caption": "Photo 9",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-9",
          "title": "Photo 9",
          "description": "Beautiful photo 9 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/picture_10.webp",
          "createdAt": "2025-07-02T11:03:25.369Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-9",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-10",
        "memoryType": "image",
        "position": 9,
        "caption": "Photo 10",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-10",
          "title": "Photo 10",
          "description": "Beautiful photo 10 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_01.webp",
          "createdAt": "2025-07-01T16:11:33.888Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-10",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-11",
        "memoryType": "image",
        "position": 10,
        "caption": "Photo 11",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-11",
          "title": "Photo 11",
          "description": "Beautiful photo 11 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_02.webp",
          "createdAt": "2025-05-06T16:48:11.906Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-11",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-12",
        "memoryType": "image",
        "position": 11,
        "caption": "Photo 12",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-12",
          "title": "Photo 12",
          "description": "Beautiful photo 12 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_07.webp",
          "createdAt": "2025-04-27T11:21:57.110Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-12",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-13",
        "memoryType": "image",
        "position": 12,
        "caption": "Photo 13",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-13",
          "title": "Photo 13",
          "description": "Beautiful photo 13 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_08.webp",
          "createdAt": "2025-04-12T23:06:41.122Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-13",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-14",
        "memoryType": "image",
        "position": 13,
        "caption": "Photo 14",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-14",
          "title": "Photo 14",
          "description": "Beautiful photo 14 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_09.webp",
          "createdAt": "2025-06-10T18:47:01.978Z",
          "metadata": {}
        }
      },
      {
        "id": "item-landscape-gallery-14",
        "galleryId": "landscape-gallery",
        "memoryId": "memory-landscape-gallery-15",
        "memoryType": "image",
        "position": 14,
        "caption": "Photo 15",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-04T15:39:42.995Z",
        "updatedAt": "2025-03-04T15:39:42.995Z",
        "memory": {
          "id": "memory-landscape-gallery-15",
          "title": "Photo 15",
          "description": "Beautiful photo 15 from Landscape Photography",
          "type": "image",
          "url": "/mock/galleries/landscape-gallery/shot_14.webp",
          "createdAt": "2025-05-03T07:52:23.205Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 15,
    "isOwner": true
  },
  {
    "id": "mixed-gallery",
    "title": "Mixed Media Gallery",
    "description": "A diverse collection of different photography styles",
    "isPublic": false,
    "createdAt": "2025-03-13T01:58:42.223Z",
    "updatedAt": "2025-03-13T01:58:42.223Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-mixed-gallery-0",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_01.webp",
          "createdAt": "2025-07-25T01:33:03.665Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-1",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_04.webp",
          "createdAt": "2025-03-31T02:48:42.365Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-2",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_05.webp",
          "createdAt": "2025-07-28T01:51:05.313Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-3",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_08.webp",
          "createdAt": "2025-06-03T11:07:05.252Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-4",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_10.webp",
          "createdAt": "2025-06-13T13:05:52.844Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-5",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-6",
        "memoryType": "image",
        "position": 5,
        "caption": "Photo 6",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-6",
          "title": "Photo 6",
          "description": "Beautiful photo 6 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_13.webp",
          "createdAt": "2025-03-15T10:29:43.505Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-6",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-7",
        "memoryType": "image",
        "position": 6,
        "caption": "Photo 7",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-7",
          "title": "Photo 7",
          "description": "Beautiful photo 7 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_18.webp",
          "createdAt": "2025-03-12T11:46:11.407Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-7",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-8",
        "memoryType": "image",
        "position": 7,
        "caption": "Photo 8",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-8",
          "title": "Photo 8",
          "description": "Beautiful photo 8 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/image_19.webp",
          "createdAt": "2025-07-31T09:10:42.364Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-8",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-9",
        "memoryType": "image",
        "position": 8,
        "caption": "Photo 9",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-9",
          "title": "Photo 9",
          "description": "Beautiful photo 9 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/photo_20.webp",
          "createdAt": "2025-07-19T15:20:00.147Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-9",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-10",
        "memoryType": "image",
        "position": 9,
        "caption": "Photo 10",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-10",
          "title": "Photo 10",
          "description": "Beautiful photo 10 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/picture_02.webp",
          "createdAt": "2025-08-20T10:09:23.995Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-10",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-11",
        "memoryType": "image",
        "position": 10,
        "caption": "Photo 11",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-11",
          "title": "Photo 11",
          "description": "Beautiful photo 11 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/picture_06.webp",
          "createdAt": "2025-04-29T10:35:49.439Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-11",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-12",
        "memoryType": "image",
        "position": 11,
        "caption": "Photo 12",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-12",
          "title": "Photo 12",
          "description": "Beautiful photo 12 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/picture_15.webp",
          "createdAt": "2025-06-13T06:21:38.526Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-12",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-13",
        "memoryType": "image",
        "position": 12,
        "caption": "Photo 13",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-13",
          "title": "Photo 13",
          "description": "Beautiful photo 13 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/picture_16.webp",
          "createdAt": "2025-06-10T21:24:29.396Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-13",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-14",
        "memoryType": "image",
        "position": 13,
        "caption": "Photo 14",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-14",
          "title": "Photo 14",
          "description": "Beautiful photo 14 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/picture_17.webp",
          "createdAt": "2025-07-28T15:55:45.978Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-14",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-15",
        "memoryType": "image",
        "position": 14,
        "caption": "Photo 15",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-15",
          "title": "Photo 15",
          "description": "Beautiful photo 15 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_03.webp",
          "createdAt": "2025-06-20T15:35:10.191Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-15",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-16",
        "memoryType": "image",
        "position": 15,
        "caption": "Photo 16",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-16",
          "title": "Photo 16",
          "description": "Beautiful photo 16 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_07.webp",
          "createdAt": "2025-04-02T05:47:39.707Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-16",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-17",
        "memoryType": "image",
        "position": 16,
        "caption": "Photo 17",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-17",
          "title": "Photo 17",
          "description": "Beautiful photo 17 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_09.webp",
          "createdAt": "2025-03-09T21:11:25.710Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-17",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-18",
        "memoryType": "image",
        "position": 17,
        "caption": "Photo 18",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-18",
          "title": "Photo 18",
          "description": "Beautiful photo 18 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_11.webp",
          "createdAt": "2025-03-28T06:20:33.484Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-18",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-19",
        "memoryType": "image",
        "position": 18,
        "caption": "Photo 19",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-19",
          "title": "Photo 19",
          "description": "Beautiful photo 19 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_12.webp",
          "createdAt": "2025-05-25T09:45:31.290Z",
          "metadata": {}
        }
      },
      {
        "id": "item-mixed-gallery-19",
        "galleryId": "mixed-gallery",
        "memoryId": "memory-mixed-gallery-20",
        "memoryType": "image",
        "position": 19,
        "caption": "Photo 20",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-03-13T01:58:42.223Z",
        "updatedAt": "2025-03-13T01:58:42.223Z",
        "memory": {
          "id": "memory-mixed-gallery-20",
          "title": "Photo 20",
          "description": "Beautiful photo 20 from Mixed Media Gallery",
          "type": "image",
          "url": "/mock/galleries/mixed-gallery/shot_14.webp",
          "createdAt": "2025-06-05T15:27:44.483Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 20,
    "isOwner": true
  },
  {
    "id": "wild-gallery",
    "title": "Wild & Free",
    "description": "Adventure and nature photography",
    "isPublic": true,
    "createdAt": "2025-08-05T15:50:23.756Z",
    "updatedAt": "2025-08-05T15:50:23.756Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-wild-gallery-0",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_03.webp",
          "createdAt": "2025-08-14T07:22:21.493Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-1",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_04.webp",
          "createdAt": "2025-08-01T09:04:34.516Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-2",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_06.webp",
          "createdAt": "2025-03-08T22:59:15.978Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-3",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_09.webp",
          "createdAt": "2025-02-26T19:04:12.043Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-4",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_16.webp",
          "createdAt": "2025-03-28T21:54:21.686Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-5",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-6",
        "memoryType": "image",
        "position": 5,
        "caption": "Photo 6",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-6",
          "title": "Photo 6",
          "description": "Beautiful photo 6 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_21.webp",
          "createdAt": "2025-05-27T19:59:58.120Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-6",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-7",
        "memoryType": "image",
        "position": 6,
        "caption": "Photo 7",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-7",
          "title": "Photo 7",
          "description": "Beautiful photo 7 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/image_24.webp",
          "createdAt": "2025-08-04T02:03:16.658Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-7",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-8",
        "memoryType": "image",
        "position": 7,
        "caption": "Photo 8",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-8",
          "title": "Photo 8",
          "description": "Beautiful photo 8 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/photo_01.webp",
          "createdAt": "2025-05-17T06:41:15.872Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-8",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-9",
        "memoryType": "image",
        "position": 8,
        "caption": "Photo 9",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-9",
          "title": "Photo 9",
          "description": "Beautiful photo 9 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/photo_13.webp",
          "createdAt": "2025-06-21T19:29:34.013Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-9",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-10",
        "memoryType": "image",
        "position": 9,
        "caption": "Photo 10",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-10",
          "title": "Photo 10",
          "description": "Beautiful photo 10 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/photo_17.webp",
          "createdAt": "2025-07-13T11:28:16.210Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-10",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-11",
        "memoryType": "image",
        "position": 10,
        "caption": "Photo 11",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-11",
          "title": "Photo 11",
          "description": "Beautiful photo 11 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/photo_18.webp",
          "createdAt": "2025-07-10T10:20:49.641Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-11",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-12",
        "memoryType": "image",
        "position": 11,
        "caption": "Photo 12",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-12",
          "title": "Photo 12",
          "description": "Beautiful photo 12 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_07.webp",
          "createdAt": "2025-06-26T03:44:38.569Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-12",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-13",
        "memoryType": "image",
        "position": 12,
        "caption": "Photo 13",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-13",
          "title": "Photo 13",
          "description": "Beautiful photo 13 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_08.webp",
          "createdAt": "2025-07-13T04:57:02.966Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-13",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-14",
        "memoryType": "image",
        "position": 13,
        "caption": "Photo 14",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-14",
          "title": "Photo 14",
          "description": "Beautiful photo 14 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_10.webp",
          "createdAt": "2025-06-05T05:28:06.938Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-14",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-15",
        "memoryType": "image",
        "position": 14,
        "caption": "Photo 15",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-15",
          "title": "Photo 15",
          "description": "Beautiful photo 15 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_11.webp",
          "createdAt": "2025-07-17T00:50:19.586Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-15",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-16",
        "memoryType": "image",
        "position": 15,
        "caption": "Photo 16",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-16",
          "title": "Photo 16",
          "description": "Beautiful photo 16 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_12.webp",
          "createdAt": "2025-07-31T17:41:12.742Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-16",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-17",
        "memoryType": "image",
        "position": 16,
        "caption": "Photo 17",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-17",
          "title": "Photo 17",
          "description": "Beautiful photo 17 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_14.webp",
          "createdAt": "2025-07-10T22:22:01.344Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-17",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-18",
        "memoryType": "image",
        "position": 17,
        "caption": "Photo 18",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-18",
          "title": "Photo 18",
          "description": "Beautiful photo 18 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_15.webp",
          "createdAt": "2025-05-21T17:18:04.714Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-18",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-19",
        "memoryType": "image",
        "position": 18,
        "caption": "Photo 19",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-19",
          "title": "Photo 19",
          "description": "Beautiful photo 19 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_20.webp",
          "createdAt": "2025-06-20T15:01:02.485Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-19",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-20",
        "memoryType": "image",
        "position": 19,
        "caption": "Photo 20",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-20",
          "title": "Photo 20",
          "description": "Beautiful photo 20 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_22.webp",
          "createdAt": "2025-05-06T13:00:25.250Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-20",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-21",
        "memoryType": "image",
        "position": 20,
        "caption": "Photo 21",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-21",
          "title": "Photo 21",
          "description": "Beautiful photo 21 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/picture_23.webp",
          "createdAt": "2025-06-20T00:35:37.184Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-21",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-22",
        "memoryType": "image",
        "position": 21,
        "caption": "Photo 22",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-22",
          "title": "Photo 22",
          "description": "Beautiful photo 22 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/shot_02.webp",
          "createdAt": "2025-03-04T02:50:48.582Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-22",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-23",
        "memoryType": "image",
        "position": 22,
        "caption": "Photo 23",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-23",
          "title": "Photo 23",
          "description": "Beautiful photo 23 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/shot_05.webp",
          "createdAt": "2025-07-10T16:00:46.380Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-23",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-24",
        "memoryType": "image",
        "position": 23,
        "caption": "Photo 24",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-24",
          "title": "Photo 24",
          "description": "Beautiful photo 24 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/shot_19.webp",
          "createdAt": "2025-06-04T05:36:30.707Z",
          "metadata": {}
        }
      },
      {
        "id": "item-wild-gallery-24",
        "galleryId": "wild-gallery",
        "memoryId": "memory-wild-gallery-25",
        "memoryType": "image",
        "position": 24,
        "caption": "Photo 25",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-05T15:50:23.756Z",
        "updatedAt": "2025-08-05T15:50:23.756Z",
        "memory": {
          "id": "memory-wild-gallery-25",
          "title": "Photo 25",
          "description": "Beautiful photo 25 from Wild & Free",
          "type": "image",
          "url": "/mock/galleries/wild-gallery/shot_25.webp",
          "createdAt": "2025-03-28T01:04:01.844Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 25,
    "isOwner": true
  },
  {
    "id": "small-gallery",
    "title": "Small Moments",
    "description": "Intimate moments captured in time",
    "isPublic": false,
    "createdAt": "2025-08-18T06:55:45.619Z",
    "updatedAt": "2025-08-18T06:55:45.619Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-small-gallery-0",
        "galleryId": "small-gallery",
        "memoryId": "memory-small-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-18T06:55:45.619Z",
        "updatedAt": "2025-08-18T06:55:45.619Z",
        "memory": {
          "id": "memory-small-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Small Moments",
          "type": "image",
          "url": "/mock/galleries/small-gallery/photo_02.webp",
          "createdAt": "2025-06-22T12:25:59.970Z",
          "metadata": {}
        }
      },
      {
        "id": "item-small-gallery-1",
        "galleryId": "small-gallery",
        "memoryId": "memory-small-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-18T06:55:45.619Z",
        "updatedAt": "2025-08-18T06:55:45.619Z",
        "memory": {
          "id": "memory-small-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Small Moments",
          "type": "image",
          "url": "/mock/galleries/small-gallery/photo_03.webp",
          "createdAt": "2025-03-26T20:42:01.752Z",
          "metadata": {}
        }
      },
      {
        "id": "item-small-gallery-2",
        "galleryId": "small-gallery",
        "memoryId": "memory-small-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-18T06:55:45.619Z",
        "updatedAt": "2025-08-18T06:55:45.619Z",
        "memory": {
          "id": "memory-small-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Small Moments",
          "type": "image",
          "url": "/mock/galleries/small-gallery/photo_04.webp",
          "createdAt": "2025-06-11T12:47:52.136Z",
          "metadata": {}
        }
      },
      {
        "id": "item-small-gallery-3",
        "galleryId": "small-gallery",
        "memoryId": "memory-small-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-18T06:55:45.619Z",
        "updatedAt": "2025-08-18T06:55:45.619Z",
        "memory": {
          "id": "memory-small-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Small Moments",
          "type": "image",
          "url": "/mock/galleries/small-gallery/picture_05.webp",
          "createdAt": "2025-08-13T18:17:34.499Z",
          "metadata": {}
        }
      },
      {
        "id": "item-small-gallery-4",
        "galleryId": "small-gallery",
        "memoryId": "memory-small-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-08-18T06:55:45.619Z",
        "updatedAt": "2025-08-18T06:55:45.619Z",
        "memory": {
          "id": "memory-small-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Small Moments",
          "type": "image",
          "url": "/mock/galleries/small-gallery/shot_01.webp",
          "createdAt": "2025-06-09T05:39:30.124Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 5,
    "isOwner": true
  },
  {
    "id": "large-gallery",
    "title": "Large Collection",
    "description": "An extensive collection of memories",
    "isPublic": true,
    "createdAt": "2025-07-10T14:11:04.275Z",
    "updatedAt": "2025-07-10T14:11:04.275Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-large-gallery-0",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_05.webp",
          "createdAt": "2025-04-19T07:48:20.612Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-1",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_13.webp",
          "createdAt": "2025-03-29T14:24:15.914Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-2",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_16.webp",
          "createdAt": "2025-03-26T10:10:47.159Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-3",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_20.webp",
          "createdAt": "2025-04-13T04:56:49.677Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-4",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_28.webp",
          "createdAt": "2025-03-03T13:28:26.482Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-5",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-6",
        "memoryType": "image",
        "position": 5,
        "caption": "Photo 6",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-6",
          "title": "Photo 6",
          "description": "Beautiful photo 6 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_32.webp",
          "createdAt": "2025-07-11T22:55:54.205Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-6",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-7",
        "memoryType": "image",
        "position": 6,
        "caption": "Photo 7",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-7",
          "title": "Photo 7",
          "description": "Beautiful photo 7 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_38.webp",
          "createdAt": "2025-07-05T16:32:49.355Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-7",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-8",
        "memoryType": "image",
        "position": 7,
        "caption": "Photo 8",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-8",
          "title": "Photo 8",
          "description": "Beautiful photo 8 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_41.webp",
          "createdAt": "2025-08-11T12:10:57.542Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-8",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-9",
        "memoryType": "image",
        "position": 8,
        "caption": "Photo 9",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-9",
          "title": "Photo 9",
          "description": "Beautiful photo 9 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_45.webp",
          "createdAt": "2025-05-23T05:14:57.443Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-9",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-10",
        "memoryType": "image",
        "position": 9,
        "caption": "Photo 10",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-10",
          "title": "Photo 10",
          "description": "Beautiful photo 10 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/image_49.webp",
          "createdAt": "2025-06-23T17:11:01.375Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-10",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-11",
        "memoryType": "image",
        "position": 10,
        "caption": "Photo 11",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-11",
          "title": "Photo 11",
          "description": "Beautiful photo 11 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_01.webp",
          "createdAt": "2025-04-03T11:43:41.303Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-11",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-12",
        "memoryType": "image",
        "position": 11,
        "caption": "Photo 12",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-12",
          "title": "Photo 12",
          "description": "Beautiful photo 12 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_04.webp",
          "createdAt": "2025-04-23T01:42:26.123Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-12",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-13",
        "memoryType": "image",
        "position": 12,
        "caption": "Photo 13",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-13",
          "title": "Photo 13",
          "description": "Beautiful photo 13 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_07.webp",
          "createdAt": "2025-04-16T13:26:48.637Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-13",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-14",
        "memoryType": "image",
        "position": 13,
        "caption": "Photo 14",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-14",
          "title": "Photo 14",
          "description": "Beautiful photo 14 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_08.webp",
          "createdAt": "2025-07-04T01:48:38.200Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-14",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-15",
        "memoryType": "image",
        "position": 14,
        "caption": "Photo 15",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-15",
          "title": "Photo 15",
          "description": "Beautiful photo 15 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_10.webp",
          "createdAt": "2025-06-12T14:33:45.463Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-15",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-16",
        "memoryType": "image",
        "position": 15,
        "caption": "Photo 16",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-16",
          "title": "Photo 16",
          "description": "Beautiful photo 16 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_18.webp",
          "createdAt": "2025-06-02T15:56:43.388Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-16",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-17",
        "memoryType": "image",
        "position": 16,
        "caption": "Photo 17",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-17",
          "title": "Photo 17",
          "description": "Beautiful photo 17 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_24.webp",
          "createdAt": "2025-02-27T13:51:13.308Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-17",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-18",
        "memoryType": "image",
        "position": 17,
        "caption": "Photo 18",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-18",
          "title": "Photo 18",
          "description": "Beautiful photo 18 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_25.webp",
          "createdAt": "2025-04-25T08:40:13.741Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-18",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-19",
        "memoryType": "image",
        "position": 18,
        "caption": "Photo 19",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-19",
          "title": "Photo 19",
          "description": "Beautiful photo 19 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_26.webp",
          "createdAt": "2025-08-03T19:34:01.440Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-19",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-20",
        "memoryType": "image",
        "position": 19,
        "caption": "Photo 20",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-20",
          "title": "Photo 20",
          "description": "Beautiful photo 20 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_30.webp",
          "createdAt": "2025-05-12T03:44:19.589Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-20",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-21",
        "memoryType": "image",
        "position": 20,
        "caption": "Photo 21",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-21",
          "title": "Photo 21",
          "description": "Beautiful photo 21 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_33.webp",
          "createdAt": "2025-04-09T08:57:18.747Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-21",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-22",
        "memoryType": "image",
        "position": 21,
        "caption": "Photo 22",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-22",
          "title": "Photo 22",
          "description": "Beautiful photo 22 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_34.webp",
          "createdAt": "2025-04-22T20:28:13.875Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-22",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-23",
        "memoryType": "image",
        "position": 22,
        "caption": "Photo 23",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-23",
          "title": "Photo 23",
          "description": "Beautiful photo 23 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_36.webp",
          "createdAt": "2025-06-21T14:05:38.447Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-23",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-24",
        "memoryType": "image",
        "position": 23,
        "caption": "Photo 24",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-24",
          "title": "Photo 24",
          "description": "Beautiful photo 24 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_44.webp",
          "createdAt": "2025-03-28T04:28:34.304Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-24",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-25",
        "memoryType": "image",
        "position": 24,
        "caption": "Photo 25",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-25",
          "title": "Photo 25",
          "description": "Beautiful photo 25 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/photo_46.webp",
          "createdAt": "2025-07-25T00:55:45.497Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-25",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-26",
        "memoryType": "image",
        "position": 25,
        "caption": "Photo 26",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-26",
          "title": "Photo 26",
          "description": "Beautiful photo 26 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_03.webp",
          "createdAt": "2025-07-17T17:21:20.457Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-26",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-27",
        "memoryType": "image",
        "position": 26,
        "caption": "Photo 27",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-27",
          "title": "Photo 27",
          "description": "Beautiful photo 27 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_09.webp",
          "createdAt": "2025-07-18T07:05:42.962Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-27",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-28",
        "memoryType": "image",
        "position": 27,
        "caption": "Photo 28",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-28",
          "title": "Photo 28",
          "description": "Beautiful photo 28 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_12.webp",
          "createdAt": "2025-04-03T19:13:18.537Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-28",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-29",
        "memoryType": "image",
        "position": 28,
        "caption": "Photo 29",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-29",
          "title": "Photo 29",
          "description": "Beautiful photo 29 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_14.webp",
          "createdAt": "2025-03-11T00:17:22.797Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-29",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-30",
        "memoryType": "image",
        "position": 29,
        "caption": "Photo 30",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-30",
          "title": "Photo 30",
          "description": "Beautiful photo 30 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_15.webp",
          "createdAt": "2025-03-22T10:13:49.317Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-30",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-31",
        "memoryType": "image",
        "position": 30,
        "caption": "Photo 31",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-31",
          "title": "Photo 31",
          "description": "Beautiful photo 31 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_19.webp",
          "createdAt": "2025-06-18T07:41:41.298Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-31",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-32",
        "memoryType": "image",
        "position": 31,
        "caption": "Photo 32",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-32",
          "title": "Photo 32",
          "description": "Beautiful photo 32 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_21.webp",
          "createdAt": "2025-05-22T06:22:52.440Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-32",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-33",
        "memoryType": "image",
        "position": 32,
        "caption": "Photo 33",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-33",
          "title": "Photo 33",
          "description": "Beautiful photo 33 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_22.webp",
          "createdAt": "2025-07-10T08:48:52.447Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-33",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-34",
        "memoryType": "image",
        "position": 33,
        "caption": "Photo 34",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-34",
          "title": "Photo 34",
          "description": "Beautiful photo 34 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_27.webp",
          "createdAt": "2025-07-30T08:17:38.488Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-34",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-35",
        "memoryType": "image",
        "position": 34,
        "caption": "Photo 35",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-35",
          "title": "Photo 35",
          "description": "Beautiful photo 35 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_29.webp",
          "createdAt": "2025-05-23T07:10:47.851Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-35",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-36",
        "memoryType": "image",
        "position": 35,
        "caption": "Photo 36",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-36",
          "title": "Photo 36",
          "description": "Beautiful photo 36 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_39.webp",
          "createdAt": "2025-06-16T21:07:32.726Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-36",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-37",
        "memoryType": "image",
        "position": 36,
        "caption": "Photo 37",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-37",
          "title": "Photo 37",
          "description": "Beautiful photo 37 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_42.webp",
          "createdAt": "2025-04-19T17:17:19.639Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-37",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-38",
        "memoryType": "image",
        "position": 37,
        "caption": "Photo 38",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-38",
          "title": "Photo 38",
          "description": "Beautiful photo 38 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_43.webp",
          "createdAt": "2025-08-22T18:22:00.443Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-38",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-39",
        "memoryType": "image",
        "position": 38,
        "caption": "Photo 39",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-39",
          "title": "Photo 39",
          "description": "Beautiful photo 39 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_47.webp",
          "createdAt": "2025-04-08T00:44:02.866Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-39",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-40",
        "memoryType": "image",
        "position": 39,
        "caption": "Photo 40",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-40",
          "title": "Photo 40",
          "description": "Beautiful photo 40 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_48.webp",
          "createdAt": "2025-05-09T20:58:23.500Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-40",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-41",
        "memoryType": "image",
        "position": 40,
        "caption": "Photo 41",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-41",
          "title": "Photo 41",
          "description": "Beautiful photo 41 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/picture_50.webp",
          "createdAt": "2025-05-20T08:29:20.906Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-41",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-42",
        "memoryType": "image",
        "position": 41,
        "caption": "Photo 42",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-42",
          "title": "Photo 42",
          "description": "Beautiful photo 42 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_02.webp",
          "createdAt": "2025-07-02T23:25:49.754Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-42",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-43",
        "memoryType": "image",
        "position": 42,
        "caption": "Photo 43",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-43",
          "title": "Photo 43",
          "description": "Beautiful photo 43 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_06.webp",
          "createdAt": "2025-04-03T17:51:58.573Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-43",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-44",
        "memoryType": "image",
        "position": 43,
        "caption": "Photo 44",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-44",
          "title": "Photo 44",
          "description": "Beautiful photo 44 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_11.webp",
          "createdAt": "2025-04-07T23:07:19.723Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-44",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-45",
        "memoryType": "image",
        "position": 44,
        "caption": "Photo 45",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-45",
          "title": "Photo 45",
          "description": "Beautiful photo 45 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_17.webp",
          "createdAt": "2025-08-20T16:31:33.591Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-45",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-46",
        "memoryType": "image",
        "position": 45,
        "caption": "Photo 46",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-46",
          "title": "Photo 46",
          "description": "Beautiful photo 46 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_23.webp",
          "createdAt": "2025-07-30T11:01:33.641Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-46",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-47",
        "memoryType": "image",
        "position": 46,
        "caption": "Photo 47",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-47",
          "title": "Photo 47",
          "description": "Beautiful photo 47 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_31.webp",
          "createdAt": "2025-04-15T08:57:34.412Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-47",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-48",
        "memoryType": "image",
        "position": 47,
        "caption": "Photo 48",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-48",
          "title": "Photo 48",
          "description": "Beautiful photo 48 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_35.webp",
          "createdAt": "2025-07-07T09:47:49.633Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-48",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-49",
        "memoryType": "image",
        "position": 48,
        "caption": "Photo 49",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-49",
          "title": "Photo 49",
          "description": "Beautiful photo 49 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_37.webp",
          "createdAt": "2025-08-24T20:28:21.363Z",
          "metadata": {}
        }
      },
      {
        "id": "item-large-gallery-49",
        "galleryId": "large-gallery",
        "memoryId": "memory-large-gallery-50",
        "memoryType": "image",
        "position": 49,
        "caption": "Photo 50",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-10T14:11:04.275Z",
        "updatedAt": "2025-07-10T14:11:04.275Z",
        "memory": {
          "id": "memory-large-gallery-50",
          "title": "Photo 50",
          "description": "Beautiful photo 50 from Large Collection",
          "type": "image",
          "url": "/mock/galleries/large-gallery/shot_40.webp",
          "createdAt": "2025-05-09T02:49:57.417Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 50,
    "isOwner": true
  },
  {
    "id": "broken-gallery",
    "title": "Broken Links Gallery",
    "description": "Testing fallback behavior with broken image links",
    "isPublic": true,
    "createdAt": "2025-07-14T09:36:06.214Z",
    "updatedAt": "2025-07-14T09:36:06.214Z",
    "ownerId": "mock-user-1",
    "items": [
      {
        "id": "item-broken-gallery-0",
        "galleryId": "broken-gallery",
        "memoryId": "memory-broken-gallery-1",
        "memoryType": "image",
        "position": 0,
        "caption": "Photo 1",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T09:36:06.214Z",
        "updatedAt": "2025-07-14T09:36:06.214Z",
        "memory": {
          "id": "memory-broken-gallery-1",
          "title": "Photo 1",
          "description": "Beautiful photo 1 from Broken Links Gallery",
          "type": "image",
          "url": "/mock/galleries/broken-gallery/broken_image_1.webp",
          "createdAt": "2025-05-22T09:56:41.867Z",
          "metadata": {}
        }
      },
      {
        "id": "item-broken-gallery-1",
        "galleryId": "broken-gallery",
        "memoryId": "memory-broken-gallery-2",
        "memoryType": "image",
        "position": 1,
        "caption": "Photo 2",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T09:36:06.214Z",
        "updatedAt": "2025-07-14T09:36:06.214Z",
        "memory": {
          "id": "memory-broken-gallery-2",
          "title": "Photo 2",
          "description": "Beautiful photo 2 from Broken Links Gallery",
          "type": "image",
          "url": "/mock/galleries/broken-gallery/missing_photo_2.webp",
          "createdAt": "2025-07-17T19:04:01.590Z",
          "metadata": {}
        }
      },
      {
        "id": "item-broken-gallery-2",
        "galleryId": "broken-gallery",
        "memoryId": "memory-broken-gallery-3",
        "memoryType": "image",
        "position": 2,
        "caption": "Photo 3",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T09:36:06.214Z",
        "updatedAt": "2025-07-14T09:36:06.214Z",
        "memory": {
          "id": "memory-broken-gallery-3",
          "title": "Photo 3",
          "description": "Beautiful photo 3 from Broken Links Gallery",
          "type": "image",
          "url": "/mock/galleries/broken-gallery/error_image_3.webp",
          "createdAt": "2025-03-02T10:00:32.611Z",
          "metadata": {}
        }
      },
      {
        "id": "item-broken-gallery-3",
        "galleryId": "broken-gallery",
        "memoryId": "memory-broken-gallery-4",
        "memoryType": "image",
        "position": 3,
        "caption": "Photo 4",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T09:36:06.214Z",
        "updatedAt": "2025-07-14T09:36:06.214Z",
        "memory": {
          "id": "memory-broken-gallery-4",
          "title": "Photo 4",
          "description": "Beautiful photo 4 from Broken Links Gallery",
          "type": "image",
          "url": "/mock/galleries/broken-gallery/not_found_4.webp",
          "createdAt": "2025-06-24T10:57:23.199Z",
          "metadata": {}
        }
      },
      {
        "id": "item-broken-gallery-4",
        "galleryId": "broken-gallery",
        "memoryId": "memory-broken-gallery-5",
        "memoryType": "image",
        "position": 4,
        "caption": "Photo 5",
        "isFeatured": false,
        "metadata": {},
        "createdAt": "2025-07-14T09:36:06.214Z",
        "updatedAt": "2025-07-14T09:36:06.214Z",
        "memory": {
          "id": "memory-broken-gallery-5",
          "title": "Photo 5",
          "description": "Beautiful photo 5 from Broken Links Gallery",
          "type": "image",
          "url": "/mock/galleries/broken-gallery/invalid_link_5.webp",
          "createdAt": "2025-04-22T03:58:46.573Z",
          "metadata": {}
        }
      }
    ],
    "imageCount": 5,
    "isOwner": true
  }
];

export const getGeneratedGallery = (id: string): GalleryWithItems | undefined => {
  return generatedGalleries.find(gallery => gallery.id === id);
};

export const getAllGeneratedGalleries = (): GalleryWithItems[] => {
  return generatedGalleries;
};
