import { Memory as BaseMemory } from "@/types/memory";

// Extended Memory interface for gallery with additional properties
interface Memory extends BaseMemory {
  tags: string[];
  isFavorite: boolean;
  views: number;
}

// Sample data using generated test images
export const sampleMemories: Memory[] = [
  {
    id: "1",
    title: "Beautiful Sunset",
    description: "A stunning sunset captured during golden hour",
    type: "image",
    url: "/gallery/Beautiful_Sunset_01.webp",
    thumbnail: "/gallery/Beautiful_Sunset_01.webp",
    createdAt: "2023-08-15",
    tags: ["sunset", "nature", "golden-hour"],
    isFavorite: true,
    views: 45,
  },
  {
    id: "2",
    title: "Amazing Mountain",
    description: "Breathtaking mountain landscape with snow peaks",
    type: "image",
    url: "/gallery/Amazing_Mountain_02.webp",
    thumbnail: "/gallery/Amazing_Mountain_02.webp",
    createdAt: "2023-06-10",
    tags: ["mountain", "landscape", "snow"],
    isFavorite: true,
    views: 128,
  },
  {
    id: "3",
    title: "Stunning Ocean",
    description: "Crystal clear ocean waters on a perfect day",
    type: "image",
    url: "/gallery/Stunning_Ocean_03.webp",
    thumbnail: "/gallery/Stunning_Ocean_03.webp",
    createdAt: "2023-05-20",
    tags: ["ocean", "water", "nature"],
    isFavorite: false,
    views: 23,
  },
  {
    id: "4",
    title: "Gorgeous Forest",
    description: "Lush green forest with morning mist",
    type: "image",
    url: "/gallery/Gorgeous_Forest_04.webp",
    thumbnail: "/gallery/Gorgeous_Forest_04.webp",
    createdAt: "2023-04-05",
    tags: ["forest", "nature", "mist"],
    isFavorite: true,
    views: 67,
  },
  {
    id: "5",
    title: "Wonderful Garden",
    description: "Colorful flowers blooming in spring",
    type: "image",
    url: "/gallery/Wonderful_Garden_05.webp",
    thumbnail: "/gallery/Wonderful_Garden_05.webp",
    createdAt: "2023-03-12",
    tags: ["garden", "flowers", "spring"],
    isFavorite: false,
    views: 34,
  },
  {
    id: "6",
    title: "Fantastic Landscape",
    description: "Rolling hills and valleys in the countryside",
    type: "image",
    url: "/gallery/Fantastic_Landscape_06.webp",
    thumbnail: "/gallery/Fantastic_Landscape_06.webp",
    createdAt: "2023-02-28",
    tags: ["landscape", "hills", "countryside"],
    isFavorite: false,
    views: 19,
  },
  {
    id: "7",
    title: "Incredible Portrait",
    description: "Professional portrait photography session",
    type: "image",
    url: "/gallery/Incredible_Portrait_07.webp",
    thumbnail: "/gallery/Incredible_Portrait_07.webp",
    createdAt: "2023-01-15",
    tags: ["portrait", "photography", "professional"],
    isFavorite: true,
    views: 89,
  },
  {
    id: "8",
    title: "Spectacular Architecture",
    description: "Modern architectural masterpiece",
    type: "image",
    url: "/gallery/Spectacular_Architecture_08.webp",
    thumbnail: "/gallery/Spectacular_Architecture_08.webp",
    createdAt: "2023-01-10",
    tags: ["architecture", "modern", "design"],
    isFavorite: false,
    views: 56,
  },
];
